challenge_name: SS
if_training: True
continue_training: False
model_path: null
saved_dir: "/home/data2/pengguohang/My_Ocean/challenge/checkpoint"
output_dir: "./output/"
save_period: 5
plot_interval: 1
device: "cuda:4"
# 训练相关参数
seed: 0
epochs: 10
pat: 30

dataset:
  region_name: 'Gulf'
  folder_path: /home/data2/pengguohang/My_Ocean/challenge
  label_path: /home/data2/pengguohang/My_Ocean/CMEMS/armor_montly_1993_2019/armor_1993_2019.nc
  reference_file: /home/data2/pengguohang/My_Ocean/challenge/oisst_monthly_201001-201904.nc
  norm: True  
  lat_min: 23
  lat_max: 50
  lon_min: -80   # 80°W , 30°W
  lon_max: -30
  seq_len: 0

dataloader:
  train_bs: 1
  val_bs: 1
  test_bs: 1
  num_workers: 0
  pin_memory: False

model:
  model_name: FNN 
  in_dim: 12  # n_channels
  out_dim: 36  # n_classes, depth
  n_units1: 1000
  n_units2: 1000
  activ: Sigmoid
  noise: 0.0
  xavier_init: 0.01
  last_activation: True
  dropout_fraction: .2 
  debug: False

optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4

scheduler:
  name: "StepLR"
  step_size: 20
  gamma: 0.9
