challenge_name: SS
if_training: True
continue_training: False
model_path: null
saved_dir: "./checkpoint/"
output_dir: "./output/"
save_period: 10
plot_interval: 1
device: "cuda:4"
# 训练相关参数
seed: 0
epochs: 50  # 原文500
pat: 30

dataset:
  region_name: 'Gulf'
  img_path: '/home/data2/pengguohang/My_Ocean/Paper/Github_Data_CNN_Multi_Mode/'
  input: 'normalized_input_physical_data_1998_2015.npy'
  label: ln_Chl_ref_norm_1998_2015.npy
  file_name: ['mean_ln_chl_norm.npy', std_ln_chl_norm.npy]
  norm: True  
  lat_min: 23
  lat_max: 50
  lon_min: -80   # 80°W , 30°W
  lon_max: -30
  seq_len: 0

dataloader:
  train_bs: 2
  val_bs: 2
  test_bs: 2
  num_workers: 0
  pin_memory: False

model:
  model_name: CNN
  in_dim: 12  # n_channels
  out_dim: 36  # n_classes, depth
  noise: 0.0
  xavier_init: 0.01
  last_activation: True
  dropout: 0.0  
  debug: False

optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4

scheduler:
  name: "StepLR"
  step_size: 20
  gamma: 0.9
